spring.application.name=backend
# Database URL (yahan apne DB ka naam 'doctor_appointment' rakhein)
spring.datasource.url=jdbc:mysql://localhost:3306/doctor_appointment
spring.datasource.username=root
spring.datasource.password=password

# Driver Class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sp1529460@gmail.com

spring.mail.password=gzbslzwzgwcdrbok 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true